name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install GLFW & GLM
        run: sudo apt-get install -y libglfw3-dev libglm-dev
      - name: Install CUDA toolkit
        run: sudo apt-get install -y nvidia-cuda-toolkit
      - name: Build normal & CUDA version
        uses: ashutoshvarma/action-cmake-build@master
        with:
            build-dir: ${{ runner.workspace }}/build
            # will set the CC & CXX for cmake
            cc: gcc
            cxx: g++
            build-type: Release
            # Extra options pass to cmake while configuring project
            configure-options: -DCMAKE_INSTALL_PREFIX=./inst -DBUILD_CUDA=1           
            # install the build using cmake --install
            install-build: true
            # run build using '-j [parallel]' to use multiple threads to build
            parallel: 14
